apiVersion: apps/v1
kind: Deployment
metadata:
  name: katalogpostaj-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katalogpostaj
  template:
    metadata:
      labels:
        app: katalogpostaj
    spec:
      containers:
        - image: loginname1/prpo:katalog-0.1
          name: katalog
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: katalog
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: katalogpostaj